routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\CareerController;

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\SettingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class,'index']);
Route::get('/career', [CareerController::class,'index']);
Route::get('/news', [NewsController::class,'index']);
Route::get('/detail-news/{news:slug}', [NewsController::class,'showDetail']);

Auth::routes([
    'verify' => true
]);

Route::prefix('admin')->namespace('Admin')->middleware('auth')->group(function(){
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('/content', '\App\Http\Controllers\Admin\ContentController');
    Route::resource('/service', '\App\Http\Controllers\Admin\ServiceController');
    Route::resource('/feature', '\App\Http\Controllers\Admin\FeatureController');
    Route::resource('/price', '\App\Http\Controllers\Admin\PriceController');
    Route::resource('/testimoni', '\App\Http\Controllers\Admin\TestimoniController');
    Route::resource('/news', '\App\Http\Controllers\Admin\NewsController');

    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
    Route::put('/profile/{id}', [ProfileController::class, 'update'])->name('profile-update');

    Route::get('/configuration', [SettingController::class, 'index'])->name('config');
    Route::post('/configuration', [SettingController::class, 'update'])->name('config-update');

});

app/Models/Content.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Content extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'title',
        'description',
        'icon',
        'tipe',
        'price',
        'image',
    ];
}

app/Http/Controllers/Admin/ContentController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Content;

class ContentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Content::where('tipe',$id)->firstOrFail();
        return view('backend.pages.content.index',[
            'item' => $item
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validated = $request->validate([
            'title' => 'required',
            'description' => 'required',
        ]);
        
        $data = $request->all();
        $item = Content::findOrFail($id);
        $item->update($data);

        return redirect()->route('content.edit','header')->with(['success' => 'Successfully updated data']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
    }
}

resources/views/backend/pages/content/index.blade.php
@extends('backend.layouts.admin')

@section('title','Content '.request()->segment(3))

@section('content')

<div class="row">
    {{-- show error --}}
    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible fade show text-white" role="alert">
            <span class="alert-icon"><i class="ni ni-like-2"></i></span>
            <span class="alert-text"><strong>Error!</strong></span>
            <p>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </p>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-dismissible fade show text-white" role="alert">
            <span class="alert-icon"><i class="ni ni-like-2"></i></span>
            <span class="alert-text"><strong>Message</strong></span>
            <p>{{$message}}</p>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <div class="card mt-4">
        <div class="card-header pb-0 p-3">
            <div class="row">
                <div class="col-12 d-flex align-items-center">
                    <h5 class="font-weight-bolder mb-0">Form {{request()->segment(3)}}</h5>
                </div>
            </div>
        </div>
        
        <div class="card-body px-0 pt-0 pb-2">
            <form action="{{route('content.update',$item->id)}}" method="POST" autocomplete="off">
                @method('PUT')
                @csrf
                <div class="row mx-2">
                    <div class="form-group">
                        <label class="form-control-label">Title</label>
                        <input class="form-control" type="text" value="{{$item->title}}" id="title" name="title">
                    </div>
                </div>
                <div class="row mx-2">
                    <div class="form-group">
                        <label class="form-control-label">About</label>
                        <textarea class="form-control my-editor" id="my-editor" name="description" rows="10">{{$item->description}}</textarea>
                    </div>
                </div>
                <div class="row mx-2">
                    <div class="form-group text-end">
                        <button type="submit" class="btn btn-primary"><i class="fas fa-check mx-1" aria-hidden="true"></i>Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

@push('scripts')
    <script src="https://cdn.ckeditor.com/4.20.1/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('my-editor');
    </script>
@endpush