routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\CareerController;

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\SettingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class,'index']);
Route::get('/career', [CareerController::class,'index']);
Route::get('/news', [NewsController::class,'index']);
Route::get('/detail-news/{news:slug}', [NewsController::class,'showDetail']);

Auth::routes([
    'verify' => true
]);

Route::prefix('admin')->namespace('Admin')->middleware('auth')->group(function(){
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('/content', '\App\Http\Controllers\Admin\ContentController');
    Route::resource('/service', '\App\Http\Controllers\Admin\ServiceController');
    Route::resource('/feature', '\App\Http\Controllers\Admin\FeatureController');
    Route::resource('/price', '\App\Http\Controllers\Admin\PriceController');
    Route::resource('/testimoni', '\App\Http\Controllers\Admin\TestimoniController');
    Route::resource('/news', '\App\Http\Controllers\Admin\NewsController');

    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
    Route::put('/profile/{id}', [ProfileController::class, 'update'])->name('profile-update');

    Route::get('/configuration', [SettingController::class, 'index'])->name('config');
    Route::post('/configuration', [SettingController::class, 'update'])->name('config-update');

});

app/Http/Controllers/Admin/TestimoniController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Testimonial;
use DataTables;

class TestimoniController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Testimonial::select(['id','title','description','position','rating','image']);
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($row){
                        $btn = '<a href="'.route('testimoni.edit',$row->id).'" class="btn btn-icon btn-2 btn-primary">
                                    <span class="btn-inner--icon"><i class="fas fa-pencil"></i></span>
                                </a>
                                <form action="'.route('testimoni.destroy',$row->id).'" class="d-inline" method="POST" autocomplete="off">
                                    '.csrf_field().'
                                    <input type="hidden" name="_method" value="DELETE">
                                    <button class="btn btn-icon btn-2 btn-danger" type="submit">
                                        <span class="btn-inner--icon"><i class="fas fa-close"></i></span>
                                    </button>
                                </form>';
                        return $btn;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
        
        return view('backend.pages.testimoni.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.pages.testimoni.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'title' => 'required',
            'position' => 'required',
            'rating' => 'required',
            'description' => 'required',
            'image' => 'required|image',
        ]);
        
        $data = $request->all();

        // upload image
        $data['image']  = $request->file('image')->store(
            'assets/testimonial/','public'
        );

        Testimonial::create($data);
        return redirect()->route('testimoni.index')->with(['success' => 'Successfully saved data']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Testimonial::findOrFail($id);
        return view('backend.pages.testimoni.edit',[
            'item' => $item
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validated = $request->validate([
            'title' => 'required',
            'position' => 'required',
            'rating' => 'required',
            'description' => 'required',
            // 'image' => 'required|image',
        ]);
        
        $data = $request->all();

        if ($request->hasFile('image')) {
            // upload image
            $data['image']  = $request->file('image')->store(
                'assets/testimonial/','public'
            );
        }

        $item = Testimonial::findOrFail($id);
        $item->update($data);

        return redirect()->route('testimoni.index')->with(['success' => 'Successfully saved updated']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Testimonial::findOrFail($id);
        $item->delete();
        return redirect()->route('testimoni.index')->with(['success' => 'Successfully deleted data']);
    }
}

resources/views/backend/pages/testimoni/create.blade.php
@extends('backend.layouts.admin')

@section('title','Add Testimonial')

@push('styles')
    <link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/css/star-rating.min.css" media="all" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/themes/krajee-svg/theme.css" media="all" rel="stylesheet" type="text/css" />
@endpush

@section('content')

<div class="row">
    {{-- show error --}}
    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible fade show text-white" role="alert">
            <span class="alert-icon"><i class="ni ni-like-2"></i></span>
            <span class="alert-text"><strong>Error!</strong></span>
            <p>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </p>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <div class="card mt-4">
        <div class="card-header pb-0 p-3">
            <div class="row">
                <div class="col-12 d-flex align-items-center">
                    <h5 class="font-weight-bolder mb-0">Form Testimoni</h5>
                </div>
            </div>
        </div>
        
        <div class="card-body px-0 pt-0 pb-4">
            <form action="{{route('testimoni.store')}}" method="POST" autocomplete="off" enctype="multipart/form-data">
                @csrf
                <div class="row mx-2">
                    <div class="form-group">
                        <label class="form-control-label">Title</label>
                        <input class="form-control" type="text" value="{{old('title')}}" id="title" name="title">
                    </div>
                </div>
                <div class="row mx-2">
                    <div class="form-group">
                        <label class="form-control-label">Position</label>
                        <input class="form-control" type="text" value="{{old('position')}}" id="position" name="position">
                    </div>
                </div>
                <div class="row mx-2">
                    <div class="form-group">
                        <label class="form-control-label">Rating</label>
                        <input class="form-control" type="text" value="{{old('rating')}}" id="rating" name="rating">
                    </div>
                </div>
                <div class="row mx-2">
                    <div class="form-group">
                        <label class="form-control-label">Description</label>
                        <textarea class="form-control my-editor" id="my-editor" name="description" rows="10">{{old('description')}}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label">Image</label>
                    <input type="file" name="image" class="form-control">
                </div>
                <div class="row mx-2">
                    <div class="form-group text-end">
                        <a href="{{route('testimoni.index')}}" type="reset" class="btn btn-danger"><i class="fas fa-times mx-1" aria-hidden="true"></i>Cancel</a>
                        <button type="submit" class="btn btn-primary"><i class="fas fa-check mx-1" aria-hidden="true"></i>Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

@push('scripts')
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/js/star-rating.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/themes/krajee-svg/theme.js"></script>
    <script>
        $("#rating").rating({
            min:1, 
            max:5, 
            step:1, 
            size:'sm',
            showCaption:false,
        });
    </script>
@endpush

resources/views/backend/pages/testimoni/edit.blade.php
@extends('backend.layouts.admin')

@section('title','Edit Testimonial')

@push('styles')
    <link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/css/star-rating.min.css" media="all" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/themes/krajee-svg/theme.css" media="all" rel="stylesheet" type="text/css" />
@endpush

@section('content')

<div class="row">
    {{-- show error --}}
    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible fade show text-white" role="alert">
            <span class="alert-icon"><i class="ni ni-like-2"></i></span>
            <span class="alert-text"><strong>Error!</strong></span>
            <p>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </p>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <div class="card mt-4">
        <div class="card-header pb-0 p-3">
            <div class="row">
                <div class="col-12 d-flex align-items-center">
                    <h5 class="font-weight-bolder mb-0">Form Edit Testimoni</h5>
                </div>
            </div>
        </div>
        
        <div class="card-body px-0 pt-0 pb-4">
            <form action="{{route('testimoni.update',$item->id)}}" method="POST" autocomplete="off" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="row mx-2">
                    <div class="form-group">
                        <label class="form-control-label">Title</label>
                        <input class="form-control" type="text" value="{{$item->title}}" id="title" name="title">
                    </div>
                </div>
                <div class="row mx-2">
                    <div class="form-group">
                        <label class="form-control-label">Position</label>
                        <input class="form-control" type="text" value="{{$item->position}}" id="position" name="position">
                    </div>
                </div>
                <div class="row mx-2">
                    <div class="form-group">
                        <label class="form-control-label">Rating</label>
                        <input class="form-control" type="text" value="{{$item->rating}}" id="rating" name="rating">
                    </div>
                </div>
                <div class="row mx-2">
                    <div class="form-group">
                        <label class="form-control-label">Description</label>
                        <textarea class="form-control my-editor" id="my-editor" name="description" rows="10">{{$item->description}}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label">Image</label>
                    <input type="file" name="image" class="form-control">
                </div>
                <div class="row mx-2">
                    <div class="form-group text-end">
                        <a href="{{route('testimoni.index')}}" type="reset" class="btn btn-danger"><i class="fas fa-times mx-1" aria-hidden="true"></i>Cancel</a>
                        <button type="submit" class="btn btn-primary"><i class="fas fa-check mx-1" aria-hidden="true"></i>Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

@push('scripts')
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/js/star-rating.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/themes/krajee-svg/theme.js"></script>
    <script>
        $("#rating").rating({
            min:1, 
            max:5, 
            step:1, 
            size:'sm',
            showCaption:false,
        });
    </script>
@endpush

resources/views/backend/pages/testimoni/index.blade.php
@extends('backend.layouts.admin')

@section('title','Testimoni')

@push('styles')
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush

@section('content')

<div class="row">

    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-dismissible fade show text-white" role="alert">
            <span class="alert-icon"><i class="ni ni-like-2"></i></span>
            <span class="alert-text"><strong>Message</strong></span>
            <p>{{$message}}</p>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    
    <div class="card mt-4">
        <div class="card-header pb-0 p-3">
            <div class="row">
                <div class="col-6 d-flex align-items-center">
                    <h5 class="font-weight-bolder mb-0">Data Testimoni</h5>
                </div>
                <div class="col-6 text-end">
                    <a class="btn bg-gradient-dark mb-0" href="{{route('testimoni.create')}}">
                        <i class="fas fa-plus mx-1" aria-hidden="true"></i>Add New Testimoni
                    </a>
                </div>
            </div>
        </div>
        
        <div class="card-body px-0 pt-0 pb-4">
            <div class="table-responsive p-0 mt-4">
                <table class="table align-items-center" id="table-testimoni">
                  <thead>
                      <tr>
                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">No</th>
                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Title</th>
                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Icon</th>
                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Testimoni</th>
                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Description</th>
                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Action</th>
                      </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript">
        $(function () {
            var table = $('#table-testimoni').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('testimoni.index') }}",
                language: {
                    paginate: {
                        next: '<i class="fa fa-angle-right"></i>',
                        previous: '<i class="fa fa-angle-left"></i>'  
                    }
                },
                columns: [
                    {
                        data: 'id', 
                        name: 'id',
                        render: function(data,type,full){
                            return full.DT_RowIndex;
                        }
                    },
                    {
                        data: 'title', 
                        name: 'title',
                        render: function(data,type,full){
                            return `
                            <div class="d-flex px-2 py-1 align-items-center">
                                <div>
                                    <img class="avatar avatar-sm me-3" src="/storage/${full.image}" alt="Testimoni">
                                </div>
                                <div class="ms-4">
                                    <h6 class="text-sm mb-0">${data}</h6>
                                </div>
                            </div>
                            `;
                        }
                    },
                    {
                        data: 'position', 
                        name: 'position'
                    },
                    {
                        data: 'rating', 
                        name: 'rating'
                    },
                    {
                        data: 'description', 
                        name: 'description',
                        render: function (data, type) {
                          return text_truncate(data,50);  
                        },
                    },
                    {data: 'action', name: 'action', orderable: true, searchable: true},
                ]
            });
        });
    </script>
@endpush